<a href="https://colab.research.google.com/github/dalessandromark/MachineLearningDeepLearnig/blob/main/provaLezione22MLDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Thu Apr  8 14:12:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch

In [ ]:
t = torch.zeros((3,3), dtype=torch.float32)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
t1 = torch.rand((64,64,3), dtype=torch.float32)
print(t1)

In [ ]:
t1.device

device(type='cpu')

In [ ]:
t1.size()

torch.Size([64, 64, 3])

In [ ]:
t1.dtype

torch.float32

In [ ]:
!nvidia-smi

Thu Apr  8 14:27:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P0    73W / 149W |    437MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
t1.size()

torch.Size([64, 64, 3])

In [ ]:
t2 = torch.ones((64,64,3), dtype=torch.float32)

In [ ]:
t2.device

device(type='cpu')

In [ ]:
t2 = t2.cuda()

In [ ]:
t3 = t1+t2

In [ ]:
t3

tensor([[[1.9845, 1.0401, 1.8447],
         [1.7477, 1.5642, 1.4768],
         [1.7175, 1.9353, 1.5508],
         ...,
         [1.9280, 1.7690, 1.3150],
         [1.6896, 1.9217, 1.7767],
         [1.0039, 1.4656, 1.5122]],

        [[1.4210, 1.6047, 1.9599],
         [1.7542, 1.7640, 1.8667],
         [1.3277, 1.3137, 1.4722],
         ...,
         [1.7939, 1.1037, 1.1986],
         [1.8248, 1.9226, 1.6150],
         [1.7292, 1.2545, 1.7880]],

        [[1.6486, 1.1580, 1.3680],
         [1.5210, 1.4810, 1.5804],
         [1.5152, 1.2648, 1.3626],
         ...,
         [1.9081, 1.9661, 1.5694],
         [1.9289, 1.9644, 1.9174],
         [1.4079, 1.4293, 1.0845]],

        ...,

        [[1.0918, 1.6101, 1.5382],
         [1.8656, 1.7885, 1.0840],
         [1.2650, 1.7249, 1.8616],
         ...,
         [1.8862, 1.9462, 1.1115],
         [1.2130, 1.0629, 1.6784],
         [1.6132, 1.4004, 1.1730]],

        [[1.4065, 1.2518, 1.8193],
         [1.6936, 1.0684, 1.7475],
         [1.

In [ ]:
t1 = t1.cuda()

In [ ]:
t1.device

device(type='cuda', index=0)

In [ ]:
!nvidia-smi

Thu Apr  8 14:27:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    73W / 149W |    437MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import numpy as np
array = np.random.rand(3,3)
print(array)
print(np.shape(array))

[[0.11368952 0.54856961 0.07211848]
 [0.6049571  0.21369458 0.1489597 ]
 [0.76346427 0.33905816 0.54636202]]
(3, 3)


In [ ]:
t = torch.from_numpy(array)
print(t)

tensor([[0.1137, 0.5486, 0.0721],
        [0.6050, 0.2137, 0.1490],
        [0.7635, 0.3391, 0.5464]], dtype=torch.float64)


In [ ]:
t.device

device(type='cpu')

In [ ]:
t = t.cuda()

In [ ]:
t

tensor([[0.1137, 0.5486, 0.0721],
        [0.6050, 0.2137, 0.1490],
        [0.7635, 0.3391, 0.5464]], device='cuda:0', dtype=torch.float64)